### ISSUE TITLE
Idea: add group 'theme' somehow

### ISSUE THREAD

**Issue by freinric** [freinric/ANTI-HURRICANE-HURRICANE-CLUB#4]
To identify more easily which variables belong to which groups.

**Comment by WaielonH** [comment]
Altair themes have been added

**Comment by WaielonH** [comment]
Added 
- `RPL_THEME1` -> Socioeconomic Status
- `RPL_THEME2` -> Household Composition & Disability
- `RPL_THEME3` -> Minority Status & Language
- `RPL_THEME4` -> Housing Type & Transportation
